version: "2.4"
services:
  reverse_proxy:
    image: doctrina_reverse_proxy
    container_name: doctrina_reverse_proxy
    build:
      context: reverse_proxy
    mem_limit: 256m
    restart: unless-stopped
    ports:
      - 80:80
    networks:
      - doctrina_network
    depends_on:
      - server
      - ui

  ui:
    image: doctrina_ui
    container_name: doctrina_ui
    build:
      context: ui
    mem_limit: 256m
    networks:
      - doctrina_network
    depends_on:
      - server

  server:
    image: doctrina_server
    container_name: doctrina_server
    build:
      context: server
    mem_limit: 1g
    restart: unless-stopped
    networks:
      - doctrina_network
    depends_on:
      - mongodb
    environment:
      - DOCTRINA_MONGODB_URI=mongodb://mongodb:27017/doctrina?retryWrites=true&w=majority
      - DOCTRINA_LOG_DESTINATIONS=stdout,mongodb

  mongodb:
    image: mongo:5.0.6-focal
    container_name: doctrina_mongodb
    mem_limit: 2g
    restart: unless-stopped
    networks:
      - doctrina_network

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.4.3
    container_name: doctrina_elasticsearch
    environment:
      - ES_JAVA_OPTS=-Xmx512m -Xms512m -Dlog4j2.formatMsgNoLookups=true
      - discovery.type=single-node
      - cluster.name=docker-cluster
      - discovery.zen.minimum_master_nodes=1
      - network.host=0.0.0.0
    mem_limit: 6g
    networks:
      - doctrina_network

  clamav:
    image: clamav/clamav:0.105.0
    container_name: labonnealternance_clamav
    mem_limit: 3g
    restart: unless-stopped
    networks:
      - labonnealternance_network
    healthcheck:
      test: [ "CMD", "/usr/local/bin/clamdcheck.sh" ]
      interval: 60s
      retries: 3
      start_period: 120s

networks:
  doctrina_network:
    name: doctrina_network
